modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="mishanguc"
version="${mod_version}"
displayName="Mishang Urban Construction"
description='''
The mod provides an amount of blocks and items that make a beautiful city, which includes roads, signs, lights, handrails, colored blocks and some useful tools. Thank you for using this mod. I'm looking forward to your suggestions.
'''
logoFile="assets/mishanguc/icon.png"
authors="SolidBlock"
displayURL="https://github.com/SolidBlock-cn/mishanguc"
issueTrackerURL="https://github.com/SolidBlock-cn/mishanguc/issues"

[[dependencies.mishanguc]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mishanguc]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"
